import { useEffect , useState} from "react";
// debounce function used to avoid floof=ding the db with queries generated by every stroke user inputs instead it will wait for half second before searching
export function useDebounce<T> (value: T, delay?: number) {
    const [debouncedValue, setDebouncedValue] = useState<T>(value);

    useEffect(() => {
        const timer = setTimeout(() => {
            setDebouncedValue(value)},
             delay || 500);
  // unmount function is the return function in useEffect
        return () => {
            clearTimeout(timer);
        }
    }, [value, delay])

    return debouncedValue;
}